[workspace]
resolver = "3"
members = ["./kornia_aprilgrid"]

[workspace.package]
authors = ["Aditya Kumar <git@adityais.dev>"]
edition = "2024"
publish = false
license = "MIT"
license-file = "../LICENSE"
