name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: "Thank you for your pull request. Unfortunately, we do not accept pull requests for this repository. This is a personal mono-repo for miscellaneous, unmaintained Rust projects. Your contribution is appreciated, but this repository is not open for external changes."
